/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gametime;

/**
 *
 * @author PaNgAn
 */

import javax.swing.*;
import java.awt.event.ActionEvent;

public class ClassSelectionFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClassSelectionFrame
     */
    
    private String selectedClass = ""; 
    
    public ClassSelectionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWarrior = new javax.swing.JButton();
        btnMage = new javax.swing.JButton();
        btnRogue = new javax.swing.JButton();
        btnConfirmClass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Class Selection");

        btnWarrior.setText("Warrior");
        btnWarrior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarriorActionPerformed(evt);
            }
        });

        btnMage.setText("Mage");
        btnMage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMageActionPerformed(evt);
            }
        });

        btnRogue.setText("Rogue");
        btnRogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRogueActionPerformed(evt);
            }
        });

        btnConfirmClass.setText("Confirm");
        btnConfirmClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnWarrior)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmClass)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMage)
                        .addGap(75, 75, 75)
                        .addComponent(btnRogue)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWarrior)
                    .addComponent(btnMage)
                    .addComponent(btnRogue))
                .addGap(34, 34, 34)
                .addComponent(btnConfirmClass)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWarriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarriorActionPerformed
        selectedClass = "Warrior";
        System.out.println("Class selected: " + selectedClass);
    }//GEN-LAST:event_btnWarriorActionPerformed

    private void btnMageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMageActionPerformed
        selectedClass = "Mage";
        System.out.println("Class selected: " + selectedClass);
    }//GEN-LAST:event_btnMageActionPerformed

    private void btnRogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRogueActionPerformed
        selectedClass = "Rogue";
        System.out.println("Class selected: " + selectedClass);
    }//GEN-LAST:event_btnRogueActionPerformed

    private void btnConfirmClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmClassActionPerformed
        System.out.println("Confirm button clicked!"); // Debugging line

    if (!selectedClass.isEmpty()) { // Ensure a class is selected
        System.out.println("Selected Class: " + selectedClass); // Debugging line
        WorldSelectionFrame worldFrame = new WorldSelectionFrame(selectedClass);
        worldFrame.setVisible(true);
        this.dispose(); // Close the class selection frame
    } else {
        JOptionPane.showMessageDialog(this, "Please select a class first!");
    }
    }//GEN-LAST:event_btnConfirmClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassSelectionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmClass;
    private javax.swing.JButton btnMage;
    private javax.swing.JButton btnRogue;
    private javax.swing.JButton btnWarrior;
    // End of variables declaration//GEN-END:variables
}
