/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gametime;

/**
 *
 * @author PaNgAn
 */

import javax.swing.*;
import java.awt.event.ActionEvent;

public class WorldSelectionFrame extends javax.swing.JFrame {

    /**
     * Creates new form WorldSelectionFrame
     */
    private String selectedClass;

    public WorldSelectionFrame(String selectedClass) {
        this.selectedClass = selectedClass;
        setTitle("World Selection");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    
        initComponents(); // Initialize components first before using lblClass

        lblClass.setText("Selected Class: " + selectedClass);
    }

    private WorldSelectionFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClass = new javax.swing.JLabel();
        btnWorld1 = new javax.swing.JButton();
        btnWorld2 = new javax.swing.JButton();
        btnWorld3 = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblClass.setText("Selected Class");

        btnWorld1.setText("World 1");
        btnWorld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorld1ActionPerformed(evt);
            }
        });

        btnWorld2.setText("World 2");
        btnWorld2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorld2ActionPerformed(evt);
            }
        });

        btnWorld3.setText("World 3");
        btnWorld3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorld3ActionPerformed(evt);
            }
        });

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReturn)
                            .addComponent(btnWorld1))
                        .addGap(47, 47, 47)
                        .addComponent(btnWorld2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnWorld3)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblClass)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWorld1)
                    .addComponent(btnWorld2)
                    .addComponent(btnWorld3))
                .addGap(56, 56, 56)
                .addComponent(btnReturn)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWorld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorld1ActionPerformed
         int response = JOptionPane.showConfirmDialog(this, "Do you want to go to World 1?", "Confirm Selection", JOptionPane.YES_NO_OPTION);
    if (response == JOptionPane.YES_OPTION) {
        // Proceed to World 1
        JOptionPane.showMessageDialog(this, "Entering World 1...");
        // Add logic to open the new frame or transition
    }
    }//GEN-LAST:event_btnWorld1ActionPerformed

    private void btnWorld2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorld2ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Do you want to go to World 2?", "Confirm Selection", JOptionPane.YES_NO_OPTION);
    if (response == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "Entering World 2...");
        // Add logic to transition
    }
    }//GEN-LAST:event_btnWorld2ActionPerformed

    private void btnWorld3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorld3ActionPerformed
         int response = JOptionPane.showConfirmDialog(this, "Do you want to go to World 3?", "Confirm Selection", JOptionPane.YES_NO_OPTION);
    if (response == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "Entering World 3...");
        // Add logic to transition
    }
    }//GEN-LAST:event_btnWorld3ActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to return to Player Class Selection?", "Confirm return", JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
            new ClassSelectionFrame().setVisible(true);
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorldSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorldSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorldSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorldSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(() -> {
        new WorldSelectionFrame("Warrior").setVisible(true); // Provide a default class name
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnWorld1;
    private javax.swing.JButton btnWorld2;
    private javax.swing.JButton btnWorld3;
    private javax.swing.JLabel lblClass;
    // End of variables declaration//GEN-END:variables
}
