/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.genericrpg;

/**
 *
 * @author levi13570
 */
public class CharSelect extends javax.swing.JFrame {

    /**
     * Creates new form CharacterSelect
     */
    public CharSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClassSelect01 = new javax.swing.JButton();
        btnClassSelect03 = new javax.swing.JButton();
        btnClassSelect02 = new javax.swing.JButton();
        lblClassName01 = new javax.swing.JLabel();
        lblClassName02 = new javax.swing.JLabel();
        lblClassName03 = new javax.swing.JLabel();
        lblChooseClass = new javax.swing.JLabel();
        lblClassStats01 = new javax.swing.JLabel();
        lblClassStats02 = new javax.swing.JLabel();
        lblClassStats03 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnClassSelect01.setText("Char Picture 01");
        btnClassSelect01.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClassSelect01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassSelect01ActionPerformed(evt);
            }
        });

        btnClassSelect03.setText("Char Picture 03");
        btnClassSelect03.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClassSelect03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassSelect03ActionPerformed(evt);
            }
        });

        btnClassSelect02.setText("Char Picture 02");
        btnClassSelect02.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClassSelect02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassSelect02ActionPerformed(evt);
            }
        });

        lblClassName01.setText("Warrior");

        lblClassName02.setText("Mage");

        lblClassName03.setText("Rogue");

        lblChooseClass.setText("Choose a class:");

        lblClassStats01.setText("STATS HERE 01");

        lblClassStats02.setText("STATS HERE 02");

        lblClassStats03.setText("STATS HERE 03");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblClassName01)
                .addGap(199, 199, 199)
                .addComponent(lblClassName02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClassName03)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChooseClass)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClassSelect01, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClassStats01))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClassSelect02, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClassStats02))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClassStats03)
                            .addComponent(btnClassSelect03, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblChooseClass)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassName01)
                    .addComponent(lblClassName02, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassName03))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClassSelect01, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClassSelect02, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClassSelect03, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassStats01)
                    .addComponent(lblClassStats02)
                    .addComponent(lblClassStats03))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClassSelect01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassSelect01ActionPerformed
        STARTFIGHT obj = new STARTFIGHT();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClassSelect01ActionPerformed

    private void btnClassSelect03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassSelect03ActionPerformed
        STARTFIGHT obj = new STARTFIGHT();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClassSelect03ActionPerformed

    private void btnClassSelect02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassSelect02ActionPerformed
        STARTFIGHT obj = new STARTFIGHT();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClassSelect02ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassSelect01;
    private javax.swing.JButton btnClassSelect02;
    private javax.swing.JButton btnClassSelect03;
    private javax.swing.JLabel lblChooseClass;
    private javax.swing.JLabel lblClassName01;
    private javax.swing.JLabel lblClassName02;
    private javax.swing.JLabel lblClassName03;
    private javax.swing.JLabel lblClassStats01;
    private javax.swing.JLabel lblClassStats02;
    private javax.swing.JLabel lblClassStats03;
    // End of variables declaration//GEN-END:variables
}
